Завдання

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [1]:
print('task 1')

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype = float)
print(a)

task 1
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [2]:
print('tast 2')

a = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]], dtype = int)
print(a)

tast 2
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
print('task 3')

a = np.random.randint(1, 10, size = (5, 5))
print(a)

task 3
[[1 9 7 2 9]
 [9 8 4 6 7]
 [3 2 2 8 7]
 [5 5 5 6 1]
 [4 3 2 9 6]]


In [4]:
print('task 4')

a = np.random.rand(4, 4)
print(a)

task 4
[[0.13666727 0.23153064 0.67502935 0.76645679]
 [0.5426119  0.93119188 0.74446788 0.23333035]
 [0.13291131 0.66051838 0.77322216 0.50444632]
 [0.19317793 0.74962182 0.16927465 0.55047989]]


In [5]:
print ('task 5')

a = np.random.randint(1, 11, size = (5))
b = np.random.randint(1, 11, size = (5))

print('Вектор 1:', a)
print('Вектор 2:', b)

sum_result = np.add(a, b)
print('Сума:', sum_result)

subtract_result = np.subtract(a, b)
print('Віднімання:', subtract_result)

multiply_result = np.multiply(a, b)
print('Множення:', multiply_result)

task 5
Вектор 1: [ 4  9 10  9  1]
Вектор 2: [8 8 6 8 3]
Сума: [12 17 16 17  4]
Віднімання: [-4  1  4  1 -2]
Множення: [32 72 60 72  3]


In [6]:
print('task 6')

a = np.random.randint(1, 11, size = (7))
b = np.random.randint(1, 11, size = (7))

scalar_results = np.dot(a, b)
print('Скалярний добуток:', scalar_results)

task 6
Скалярний добуток: 130


In [7]:
print('tast 8')

matrix = np.random.randint(1, 11, size=(3, 3))
print('Початкова матриця:')
print(matrix)

inv_matrix = np.linalg.inv(matrix)
print('Обернена матриця:')
print(inv_matrix)


tast 8
Початкова матриця:
[[ 3  2  3]
 [ 8  2 10]
 [ 7  2  8]]
Обернена матриця:
[[-0.66666667 -1.66666667  2.33333333]
 [ 1.          0.5        -1.        ]
 [ 0.33333333  1.33333333 -1.66666667]]


In [8]:
print('task 9')

matrix = np.random.rand(4, 4)
print('Початкова матриця:')
print(matrix)

matrix_transpose = matrix.T
print('Транспонована матриця:')
print(matrix_transpose)

task 9
Початкова матриця:
[[0.94861073 0.72166133 0.42560696 0.17048029]
 [0.69976594 0.9749724  0.94356712 0.13006422]
 [0.10262061 0.13646629 0.95518254 0.5017693 ]
 [0.92075762 0.60614169 0.3317951  0.15521678]]
Транспонована матриця:
[[0.94861073 0.69976594 0.10262061 0.92075762]
 [0.72166133 0.9749724  0.13646629 0.60614169]
 [0.42560696 0.94356712 0.95518254 0.3317951 ]
 [0.17048029 0.13006422 0.5017693  0.15521678]]


In [9]:
print('task 10')

matrix = np.random.randint(1, 11, size=(3, 4))
a = np.random.randint(1, 11, size=(4))

multiply_result = np.multiply(matrix, a)
print('Перемноження:')
print(multiply_result)

task 10
Перемноження:
[[80 54 80 16]
 [20 30 50 24]
 [20 18 70 80]]


In [10]:
print('task 11')

matrix = np.random.rand(2, 3)
a = np.random.rand(3)

multiply_result = np.multiply(matrix, a)
print('Перемноження:')
print(multiply_result)

task 11
Перемноження:
[[0.91855718 0.08243688 0.21955725]
 [0.69597655 0.0360062  0.12273758]]


In [11]:
print('task 12')

matrix_1 = np.random.randint(1, 11, size=(2, 2))
print('Перша матриця:')
print(matrix_1)

matrix_2 = np.random.randint(1, 11, size=(2, 2))
print('Друга матриця:')
print (matrix_2)

multiply_result = np.multiply(matrix_1, matrix_2)
print('Перемноження:')
print(multiply_result)

task 12
Перша матриця:
[[4 5]
 [4 9]]
Друга матриця:
[[3 5]
 [2 3]]
Перемноження:
[[12 25]
 [ 8 27]]


In [12]:
print('task 13')

matrix_1 = np.random.randint(1, 11, size=(2, 2))
print('Перша матриця:')
print(matrix_1)

matrix_2 = np.random.randint(1, 11, size=(2, 2))
print('Друга матриця:')
print (matrix_2)

dot_result = np.dot(matrix_1, matrix_2)
print('Добуток:')
print(dot_result)

task 13
Перша матриця:
[[3 2]
 [3 7]]
Друга матриця:
[[ 4  2]
 [10  2]]
Добуток:
[[32 10]
 [82 20]]


In [13]:
print ('task 14')

matrix = np.random.randint(1, 101, size=(5, 5))
print('Сума елементів:', matrix.sum())

task 14
Сума елементів: 1282


In [14]:
print ('task 15')

matrix_1 = np.random.randint(1, 11, size = (4, 4))
print('Перша матриця:')
print(matrix_1)

matrix_2 = np.random.randint(1, 11, size = (4, 4))
print('Друга матриця:')
print(matrix_2)

subtract_result = np.subtract(matrix_1, matrix_2)
print('Різниця:')
print(subtract_result)

task 15
Перша матриця:
[[ 2  8 10  2]
 [ 9  3  9  8]
 [ 5  8  8  9]
 [ 8  8  5  1]]
Друга матриця:
[[ 2  2  7 10]
 [ 1  5  3  4]
 [ 7  8  2  3]
 [ 5  8  5  9]]
Різниця:
[[ 0  6  3 -8]
 [ 8 -2  6  4]
 [-2  0  6  6]
 [ 3  0  0 -8]]


In [15]:
print('task 16')

matrix = np.random.rand(3, 3)
print("Початкова матриця:")
print(matrix)


row_sums = np.sum(matrix, axis=1, keepdims=True)
print('Вектор-стовпчик з сумами елементів кожного рядка:')
print(row_sums)


task 16
Початкова матриця:
[[0.59263393 0.18304458 0.1787747 ]
 [0.60658077 0.02542924 0.46298368]
 [0.17579495 0.90562528 0.96042034]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[0.95445321]
 [1.09499369]
 [2.04184056]]


In [16]:
print('task 17')

matrix = np.random.randint(1, 11, size=(3, 4))
print("Початкова матриця:")
print(matrix)

squared_matrix = np.square(matrix)

print("Матриця з квадратами чисел:")
print(squared_matrix)


task 17
Початкова матриця:
[[10  6 10  4]
 [10  2  8  9]
 [ 8  4  5  5]]
Матриця з квадратами чисел:
[[100  36 100  16]
 [100   4  64  81]
 [ 64  16  25  25]]


In [17]:
print('task 18')

vector = np.random.randint(1, 51, size=(4))
print("Початковий вектор:")
print(vector)

vector_sqrt = np.sqrt(vector)
print("Вектор з квадратними коренями:")
print(vector_sqrt)


task 18
Початковий вектор:
[ 9 35  3 42]
Вектор з квадратними коренями:
[3.         5.91607978 1.73205081 6.4807407 ]
